openapi: "3.0.1"
info:
  title: "New User Enrollment API"
  version: "v1.0"
paths:
  /enroll-user:
    post:
      responses:
        '201':
          description: User email has been confirmed and database has been updated accordingly
          content:
            application/json: {}
        '400':
          description: Bad Request
          content:
            application/json: {}
        '404':
          description: User Not Found
          content:
            application/json: {}
        '405':
          description: Invalid httpMethod
          content:
            application/json: {}
        '500':
          description: Invalid httpMethod
          content:
            application/json: { }
        default:
          description: "Error",
          content:
            'application/json': {}
      x-amazon-apigateway-integration:
        integrationSubtype: "StepFunctions-StartSyncExecution"
        credentials:
          Fn::GetAtt: [HttpApiRole, Arn]
        requestParameters:
          Input: "$request.body"
          StateMachineArn:
            Fn::GetAtt: [NewUserEnrollmentStateMachine, Arn]
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        connectionType: "INTERNET"
        httpMethod: "POST"
x-amazon-apigateway-cors:
  allowMethods:
    - "*"
  maxAge: 0
  allowCredentials: false
  allowOrigins:
    - "*"
x-amazon-apigateway-importexport-version: "1.0"