openapi: "3.0.1"
info:
  title: "New User Enrollment API"
  version: "v1.0"
paths:
  "/enroll-user":
    post:
      responses:
        default:
          description: "Default Response For Post /",
      x-amazon-apigateway-integration:
        integrationSubtype: "StepFunctions-StartSyncExecution"
        credentials:
          Fn::GetAtt: [HttpApiRole, Arn]
        requestParameters:
          Input: "$request.body"
          StateMachineArn:
            Fn::GetAtt: [NewUserEnrollmentStateMachine, Arn]
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        connectionType: "INTERNET"
x-amazon-apigateway-cors:
  allowMethods:
    - "POST"
  maxAge: 0
  allowCredentials: false
  allowOrigins:
    - "*"
x-amazon-apigateway-importexport-version: "1.0"